In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
sns.set()

from sklearn.linear_model import LinearRegression

In [4]:
os.getcwd()

'/Users/SteveAhn/Downloads/1.DataAnalyst/Python/PythonData'

In [3]:
os.chdir(r"/Users/SteveAhn/Downloads/1.DataAnalyst/Python/PythonData")

In [5]:
data = pd.read_csv("MlinearRegression.csv")

In [6]:
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [7]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

Create the multiple linear regression

In [8]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

Standardization

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()

In [11]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
x_scaled = scaler.transform(x)

Multiple Linear Regression

In [17]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [22]:
reg.intercept_

0.29603261264909486

Creating a summary table

In [26]:
reg_summary = pd.DataFrame([['Intercept'],['SAT'], ['Rand 1,2,3']], columns = ['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [27]:
reg_summary

Features   Weights
0   Intercept  0.296033
1         SAT  0.001654
2  Rand 1,2,3 -0.008270

Making Predictions with standardized coefficients

In [28]:
new_data = pd.DataFrame([[1700,2],[1800,1]], columns = ['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [29]:
reg.predict(new_data)

array([3.09051403, 3.26413803])

In [30]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [31]:
reg.predict(new_data_scaled)

array([0.29429982, 0.30561941])

What if we removed the Rand 1,2,3 variable

In [32]:
reg_simple = LinearRegression()

In [34]:
x_simp_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simp_matrix, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [35]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])